### PR TITLE
Unraid xml

### PR DESCRIPTION
**Pull request by Serph91P**
added Unraid xml and favicon

### CODE REVIEW

**Comment by Serph91P** [comment]
@MrBrax here the promissed pull request for the unraid xml and Icon

**Review by MrBrax — CHANGES_REQUESTED** [review]
The image link should probably be to the image file, right now it links to the page with the image.

Maybe a separate folder for this, like `unraid`? To make it clear what the xml file refers to.

**Comment by Serph91P** [comment]
> The image link should probably be to the image file, right now it links to the page with the image.
> 
> Maybe a separate folder for this, like `unraid`? To make it clear what the xml file refers to.

ok folder makes sense, the image was on purpose, because if the xml actually gets into the Unraid Community Applications this would not be loaded

**Comment by MrBrax** [comment]
nice. i might change the app name in the future, we'll see

**Comment by Serph91P** [comment]
changed the image to imgur, now it stays there even if you change the name.

**Comment by MrBrax** [comment]
fyi imgur deletes images after a while, probably when nobody views it

**Pull request merged**
